AllCops:
  Exclude:
    - lib/mlibrary_search_parser.rb


# I hate this. Hate it.
Style/StringLiterals:
  Enabled: false

# Often added for clarity
Style/RedundantParentheses:
  Enabled: false

# Can make for too much indentation
Style/ClassAndModuleChildren:
  Enabled: false

# We never use method name `set_*` unless we
# really need to show something weird is
# happening, so don't disallow it
Naming/AccessorMethodName:
  Enabled: false

# I don't understand the desire to use ! instead of `not`
# The former is so much easier to miss when scanning code.
Style/Not:
  Enabled: false

# Use of an explicit if block is generally chosen
# in special cases for readability -- trust the
# programmer on this one
Style/IfUnlessModifier:
  Enabled: false

# Switching between interpolation and `to_s` is a pain
# compared to just adding/removing stuff between the
# double-quotes. Ditto with %[qQ]
Style/RedundantInterpolation:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false




